=== whacked/json-schema-cli-benchmarks/experiments/draft-04/cases/object_wide_M_valid/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "additionalProperties": false,
  "properties": {
    "k0000": {
      "type": "integer"
    },
    "k0001": {
      "type": "integer"
    },
    "k0002": {
      "type": "integer"
    },
    "k0003": {
      "type": "integer"
    },
    "k0004": {
      "type": "integer"
    },
    "k0005": {
      "type": "integer"
    },
    "k0006": {
      "type": "integer"
    },
    "k0007": {
      "type": "integer"
    },
    "k0008": {
      "type": "integer"
    },
    "k0009": {
      "type": "integer"
    },
    "k0010": {
      "type": "integer"
    },
    "k0011": {
      "type": "integer"
    },
    "k0012": {
      "type": "integer"
    },
    "k0013": {
      "type": "integer"
    },
    "k0014": {
      "type": "integer"
    },
    "k0015": {
      "type": "integer"
    },
    "k0016": {
      "type": "integer"
    },
    "k0017": {
      "type": "integer"
    },
    "k0018": {
      "type": "integer"
    },
    "k0019": {
      "type": "integer"
    },
    "k0020": {
      "type": "integer"
    },
    "k0021": {
      "type": "integer"
    },
    "k0022": {
      "type": "integer"
    },
    "k0023": {
      "type": "integer"
    },
    "k0024": {
      "type": "integer"
    },
    "k0025": {
      "type": "integer"
    },
    "k0026": {
      "type": "integer"
    },
    "k0027": {
      "type": "integer"
    },
    "k0028": {
      "type": "integer"
    },
    "k0029": {
      "type": "integer"
    },
    "k0030": {
      "type": "integer"
    },
    "k0031": {
      "type": "integer"
    },
    "k0032": {
      "type": "integer"
    },
    "k0033": {
      "type": "integer"
    },
    "k0034": {
      "type": "integer"
    },
    "k0035": {
      "type": "integer"
    },
    "k0036": {
      "type": "integer"
    },
    "k0037": {
      "type": "integer"
    },
    "k0038": {
      "type": "integer"
    },
    "k0039": {
      "type": "integer"
    },
    "k0040": {
      "type": "integer"
    },
    "k0041": {
      "type": "integer"
    },
    "k0042": {
      "type": "integer"
    },
    "k0043": {
      "type": "integer"
    },
    "k0044": {
      "type": "integer"
    },
    "k0045": {
      "type": "integer"
    },
    "k0046": {
      "type": "integer"
    },
    "k0047": {
      "type": "integer"
    },
    "k0048": {
      "type": "integer"
    },
    "k0049": {
      "type": "integer"
    },
    "k0050": {
      "type": "integer"
    },
    "k0051": {
      "type": "integer"
    },
    "k0052": {
      "type": "integer"
    },
    "k0053": {
      "type": "integer"
    },
    "k0054": {
      "type": "integer"
    },
    "k0055": {
      "type": "integer"
    },
    "k0056": {
      "type": "integer"
    },
    "k0057": {
      "type": "integer"
    },
    "k0058": {
      "type": "integer"
    },
    "k0059": {
      "type": "integer"
    },
    "k0060": {
      "type": "integer"
    },
    "k0061": {
      "type": "integer"
    },
    "k0062": {
      "type": "integer"
    },
    "k0063": {
      "type": "integer"
    },
    "k0064": {
      "type": "integer"
    },
    "k0065": {
      "type": "integer"
    },
    "k0066": {
      "type": "integer"
    },
    "k0067": {
      "type": "integer"
    },
    "k0068": {
      "type": "integer"
    },
    "k0069": {
      "type": "integer"
    },
    "k0070": {
      "type": "integer"
    },
    "k0071": {
      "type": "integer"
    },
    "k0072": {
      "type": "integer"
    },
    "k0073": {
      "type": "integer"
    },
    "k0074": {
      "type": "integer"
    },
    "k0075": {
      "type": "integer"
    },
    "k0076": {
      "type": "integer"
    },
    "k0077": {
      "type": "integer"
    },
    "k0078": {
      "type": "integer"
    },
    "k0079": {
      "type": "integer"
    },
    "k0080": {
      "type": "integer"
    },
    "k0081": {
      "type": "integer"
    },
    "k0082": {
      "type": "integer"
    },
    "k0083": {
      "type": "integer"
    },
    "k0084": {
      "type": "integer"
    },
    "k0085": {
      "type": "integer"
    },
    "k0086": {
      "type": "integer"
    },
    "k0087": {
      "type": "integer"
    },
    "k0088": {
      "type": "integer"
    },
    "k0089": {
      "type": "integer"
    },
    "k0090": {
      "type": "integer"
    },
    "k0091": {
      "type": "integer"
    },
    "k0092": {
      "type": "integer"
    },
    "k0093": {
      "type": "integer"
    },
    "k0094": {
      "type": "integer"
    },
    "k0095": {
      "type": "integer"
    },
    "k0096": {
      "type": "integer"
    },
    "k0097": {
      "type": "integer"
    },
    "k0098": {
      "type": "integer"
    },
    "k0099": {
      "type": "integer"
    },
    "k0100": {
      "type": "integer"
    },
    "k0101": {
      "type": "integer"
    },
    "k0102": {
      "type": "integer"
    },
    "k0103": {
      "type": "integer"
    },
    "k0104": {
      "type": "integer"
    },
    "k0105": {
      "type": "integer"
    },
    "k0106": {
      "type": "integer"
    },
    "k0107": {
      "type": "integer"
    },
    "k0108": {
      "type": "integer"
    },
    "k0109": {
      "type": "integer"
    },
    "k0110": {
      "type": "integer"
    },
    "k0111": {
      "type": "integer"
    },
    "k0112": {
      "type": "integer"
    },
    "k0113": {
      "type": "integer"
    },
    "k0114": {
      "type": "integer"
    },
    "k0115": {
      "type": "integer"
    },
    "k0116": {
      "type": "integer"
    },
    "k0117": {
      "type": "integer"
    },
    "k0118": {
      "type": "integer"
    },
    "k0119": {
      "type": "integer"
    },
    "k0120": {
      "type": "integer"
    },
    "k0121": {
      "type": "integer"
    },
    "k0122": {
      "type": "integer"
    },
    "k0123": {
      "type": "integer"
    },
    "k0124": {
      "type": "integer"
    },
    "k0125": {
      "type": "integer"
    },
    "k0126": {
      "type": "integer"
    },
    "k0127": {
      "type": "integer"
    }
  },
  "required": [
    "k0000",
    "k0001",
    "k0002",
    "k0003",
    "k0004",
    "k0005",
    "k0006",
    "k0007",
    "k0008",
    "k0009",
    "k0010",
    "k0011",
    "k0012",
    "k0013",
    "k0014",
    "k0015",
    "k0016",
    "k0017",
    "k0018",
    "k0019",
    "k0020",
    "k0021",
    "k0022",
    "k0023",
    "k0024",
    "k0025",
    "k0026",
    "k0027",
    "k0028",
    "k0029",
    "k0030",
    "k0031"
  ],
  "type": "object"
}

=== whacked/json-schema-cli-benchmarks/experiments/draft-04/cases/object_wide_M_valid/instances/gen_0015.json
{
  "k0000": 6099,
  "k0001": 8814,
  "k0002": 5764,
  "k0003": 5560,
  "k0004": 7852,
  "k0005": 9173,
  "k0006": 3029,
  "k0007": 9713,
  "k0008": 5212,
  "k0009": 7302,
  "k0010": 8485,
  "k0011": 3035,
  "k0012": 3761,
  "k0013": 2853,
  "k0014": 6473,
  "k0015": 107,
  "k0016": 8486,
  "k0017": 5394,
  "k0018": 5127,
  "k0019": 7149,
  "k0020": 853,
  "k0021": 7078,
  "k0022": 3219,
  "k0023": 242,
  "k0024": 5353,
  "k0025": 1081,
  "k0026": 7972,
  "k0027": 7650,
  "k0028": 2872,
  "k0029": 8660,
  "k0030": 7251,
  "k0031": 4332,
  "k0033": 6712,
  "k0034": 684,
  "k0036": 1629,
  "k0038": 8924,
  "k0039": 4929,
  "k0042": 774,
  "k0045": 4849,
  "k0046": 6644,
  "k0047": 8043,
  "k0048": 7318,
  "k0052": 3828,
  "k0054": 8476,
  "k0055": 9046,
  "k0056": 6212,
  "k0064": 7602,
  "k0067": 241,
  "k0069": 2440,
  "k0071": 4575,
  "k0075": 8893,
  "k0076": 5448,
  "k0078": 4257,
  "k0079": 3219,
  "k0080": 1078,
  "k0081": 1691,
  "k0082": 5844,
  "k0086": 9732,
  "k0087": 281,
  "k0089": 6850,
  "k0094": 8612,
  "k0099": 4298,
  "k0102": 4568,
  "k0104": 2937,
  "k0105": 9294,
  "k0108": 7609,
  "k0111": 6893,
  "k0112": 2066,
  "k0113": 7540,
  "k0115": 5111,
  "k0117": 478,
  "k0118": 5252,
  "k0120": 5697,
  "k0121": 7564
}
