=== whacked/json-schema-cli-benchmarks/experiments/draft-04/cases/array_objects_M_valid/schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "items": {
    "additionalProperties": false,
    "properties": {
      "f0": {
        "type": "integer"
      },
      "f1": {
        "type": "integer"
      },
      "f2": {
        "type": "integer"
      },
      "f3": {
        "type": "integer"
      },
      "f4": {
        "type": "integer"
      },
      "f5": {
        "type": "integer"
      },
      "f6": {
        "type": "integer"
      },
      "f7": {
        "type": "integer"
      }
    },
    "required": [
      "f0",
      "f1",
      "f2",
      "f3",
      "f4",
      "f5",
      "f6",
      "f7"
    ],
    "type": "object"
  },
  "maxItems": 1024,
  "minItems": 1024,
  "type": "array"
}

=== whacked/json-schema-cli-benchmarks/experiments/draft-04/cases/array_objects_M_valid/instances/gen_0019.json
[
  {
    "f0": 8050,
    "f1": 7982,
    "f2": 2873,
    "f3": 9132,
    "f4": 2164,
    "f5": 756,
    "f6": 711,
    "f7": 7230
  },
  {
    "f0": 88,
    "f1": 5521,
    "f2": 2667,
    "f3": 3678,
    "f4": 6128,
    "f5": 6497,
    "f6": 1276,
    "f7": 9751
  },
  {
    "f0": 9848,
    "f1": 7520,
    "f2": 9719,
    "f3": 1227,
    "f4": 1118,
    "f5": 8804,
    "f6": 4582,
    "f7": 8091
  },
  {
    "f0": 4778,
    "f1": 1467,
    "f2": 6167,
    "f3": 7599,
    "f4": 9069,
    "f5": 5105,
    "f6": 1783,
    "f7": 5272
  },
  {
    "f0": 5969,
    "f1": 2538,
    "f2": 9898,
    "f3": 7536,
    "f4": 5543,
    "f5": 4124,
    "f6": 665,
    "f7": 3288
  },
  {
    "f0": 695,
    "f1": 1347,
    "f2": 2923,
    "f3": 1178,
    "f4": 6429,
    "f5": 4137,
    "f6": 3252,
    "f7": 9215
  },
  {
    "f0": 7847,
    "f1": 849,
    "f2": 2931,
    "f3": 8958,
    "f4": 4241,
    "f5": 5664,
    "f6": 5008,
    "f7": 3550
  },
  {
    "f0": 4315,
    "f1": 3169,
    "f2": 2769,
    "f3": 1836,
    "f4": 3003,
    "f5": 7486,
    "f6": 2785,
    "f7": 75
  },
  {
    "f0": 8417,
    "f1": 6985,
    "f2": 7688,
    "f3": 1340,
    "f4": 2381,
    "f5": 3327,
    "f6": 7565,
    "f7": 3171
  },
  {
    "f0": 7615,
    "f1": 2373,
    "f2": 3244,
    "f3": 9269,
    "f4": 4298,
    "f5": 4692,
    "f6": 4314,
    "f7": 900
  },
  {
    "f0": 3802,
    "f1": 4489,
    "f2": 6330,
    "f3": 8727,
    "f4": 5991,
    "f5": 8675,
    "f6": 6120,
    "f7": 8127
  },
  {
    "f0": 6888,
    "f1": 9058,
    "f2": 1905,
    "f3": 8348,
    "f4": 5707,
    "f5": 1122,
    "f6": 6009,
    "f7": 1938
  },
  {
    "f0": 4298,
    "f1": 5495,
    "f2": 642,
    "f3": 4770,
    "f4": 1561,
    "f5": 8862,
    "f6": 1097,
    "f7": 6806
  },
  {
    "f0": 3717,
    "f1": 1304,
    "f2": 7845,
    "f3": 633,
    "f4": 8820,
    "f5": 8162,
    "f6": 4736,
    "f7": 6161
  },
  {
    "f0": 167,
    "f1": 6957,
    "f2": 7298,
    "f3": 3713,
    "f4": 1556,
    "f5": 3428,
    "f6": 8805,
    "f7": 6825
  },
  {
    "f0": 1992,
    "f1": 6345,
    "f2": 37,
    "f3": 8403,
    "f4": 2580,
    "f5": 1258,
    "f6": 8934,
    "f7": 332
  },
  {
    "f0": 3155,
    "f1": 1923,
    "f2": 5689,
    "f3": 9741,
    "f4": 6896,
    "f5": 7241,
    "f6": 7888,
    "f7": 6380
  },
  {
    "f0": 8186,
    "f1": 3054,
    "f2": 9985,
    "f3": 9118,
    "f4": 8053,
    "f5": 6771,
    "f6": 4586,
    "f7": 6080
  },
  {
    "f0": 8751,
    "f1": 8383,
    "f2": 2166,
    "f3": 5238,
    "f4": 5315,
    "f5": 2526,
    "f6": 1524,
    "f7": 5420
  },
  {
    "f0": 9008,
    "f1": 3792,
    "f2": 9394,
    "f3": 7584,
    "f4": 9144,
    "f5": 3456,
    "f6": 6566,
    "f7": 8220
  },
  {
    "f0": 9920,
    "f1": 3766,
    "f2": 2373,
    "f3": 3911,
    "f4": 5038,
    "f5": 5866,
    "f6": 4071,
    "f7": 167
  },
  {
    "f0": 8571,
    "f1": 4470,
    "f2": 3721,
    "f3": 3768,
    "f4": 1010,
    "f5": 2539,
    "f6": 8591,
    "f7": 3759
  },
  {
    "f0": 8443,
    "f1": 2545,
    "f2": 9120,
    "f3": 3454,
    "f4": 861,
    "f5": 974,
    "f6": 6170,
    "f7": 7095
  },
  {
    "f0": 6002,
    "f1": 9773,
    "f2": 6304,
    "f3": 2215,
    "f4": 8780,
    "f5": 3911,
    "f6": 5803,
    "f7": 3496
  },
  {
    "f0": 4997,
    "f1": 8730,
    "f2": 9916,
    "f3": 146,
    "f4": 4647,
    "f5": 750,
    "f6": 7555,
    "f7": 199
  },
  {
    "f0": 6124,
    "f1": 9064,
    "f2": 5888,
    "f3": 998,
    "f4": 4977,
    "f5": 2279,
    "f6": 8772,
    "f7": 404
  },
  {
    "f0": 4393,
    "f1": 2438,
    "f2": 2145,
    "f3": 7212,
    "f4": 1083,
    "f5": 823,
    "f6": 7771,
    "f7": 1936
  },
  {
    "f0": 9260,
    "f1": 3987,
    "f2": 6264,
    "f3": 4303,
    "f4": 1719,
    "f5": 8545,
    "f6": 1251,
    "f7": 689
  },
  {
    "f0": 7203,
    "f1": 3810,
    "f2": 7090,
    "f3": 2207,
    "f4": 2556,
    "f5": 5717,
    "f6": 9211,
    "f7": 9609
  },
  {
    "f0": 5648,
    "f1": 3571,
    "f2": 373,
    "f3": 7970,
    "f4": 5926,
    "f5": 3144,
    "f6": 8042,
    "f7": 6174
  },
  {
    "f0": 9031,
    "f1": 3876,
    "f2": 7174,
    "f3": 742,
    "f4": 3446,
    "f5": 3730,
    "f6": 8453,
    "f7": 2660
  },
  {
    "f0": 1586,
    "f1": 8833,
    "f2": 8678,
    "f3": 9885,
    "f4": 821,
    "f5": 793,
    "f6": 162,
    "f7": 6405
  },
  {
    "f0": 6582,
    "f1": 6454,
    "f2": 5666,
    "f3": 3956,
    "f4": 8001,
    "f5": 6848,
    "f6": 1114,
    "f7": 3917
  },
  {
    "f0": 6378,
    "f1": 4638,
    "f2": 5217,
    "f3": 1195,
    "f4": 6951,
    "f5": 7667,
    "f6": 6590,
    "f7": 9596
  },
  {
    "f0": 8559,
    "f1": 9825,
    "f2": 8627,
    "f3": 9430,
    "f4": 4841,
    "f5": 9642,
    "f6": 2835,
    "f7": 7491
  },
  {
    "f0": 8778,
    "f1": 444,
    "f2": 7344,
    "f3": 3337,
    "f4": 9453,
    "f5": 9078,
    "f6": 7637,
    "f7": 1346
  },
  {
    "f0": 2923,
    "f1": 119,
    "f2": 4148,
    "f3": 3255,
    "f4": 6185,
    "f5": 8396,
    "f6": 181,
    "f7": 4495
  },
  {
    "f0": 9842,
    "f1": 1694,
    "f2": 4122,
    "f3": 8832,
    "f4": 3774,
    "f5": 8565,
    "f6": 8912,
    "f7": 5415
  },
  {
    "f0": 3856,
    "f1": 9722,
    "f2": 6029,
    "f3": 90,
    "f4": 3322,
    "f5": 4430,
    "f6": 1372,
    "f7": 9390
  },
  {
    "f0": 4561,
    "f1": 8170,
    "f2": 7171,
    "f3": 3251,
    "f4": 994,
    "f5": 416,
    "f6": 8004,
    "f7": 6080
  },
  {
    "f0": 3801,
    "f1": 4636,
    "f2": 4997,
    "f3": 5841,
    "f4": 7888,
    "f5": 9991,
    "f6": 576,
    "f7": 988
  },
  {
    "f0": 7229,
    "f1": 976,
    "f2": 7717,
    "f3": 8152,
    "f4": 473,
    "f5": 8027,
    "f6": 914,
    "f7": 9625
  },
  {
    "f0": 3536,
    "f1": 9440,
    "f2": 2308,
    "f3": 5999,
    "f4": 8819,
    "f5": 7267,
    "f6": 7830,
    "f7": 790
  },
  {
    "f0": 914,
    "f1": 1170,
    "f2": 7963,
    "f3": 7713,
    "f4": 2033,
    "f5": 3120,
    "f6": 7402,
    "f7": 6649
  },
  {
    "f0": 5376,
    "f1": 8684,
    "f2": 248,
    "f3": 8119,
    "f4": 5347,
    "f5": 7873,
    "f6": 9972,
    "f7": 1710
  },
  {
    "f0": 3737,
    "f1": 6555,
    "f2": 3913,
    "f3": 2845,
    "f4": 592,
    "f5": 4455,
    "f6": 9023,
    "f7": 9117
  },
  {
    "f0": 4552,
    "f1": 6430,
    "f2": 5285,
    "f3": 9040,
    "f4": 1528,
    "f5": 2435,
    "f6": 2375,
    "f7": 2492
  },
  {
    "f0": 6851,
    "f1": 6044,
    "f2": 7004,
    "f3": 8875,
    "f4": 6788,
    "f5": 1876,
    "f6": 8063,
    "f7": 5026
  },
  {
    "f0": 7908,
    "f1": 4800,
    "f2": 6087,
    "f3": 6517,
    "f4": 6366,
    "f5": 2552,
    "f6": 2909,
    "f7": 6278
  },
  {
    "f0": 8687,
    "f1": 6700,
    "f2": 9619,
    "f3": 9789,
    "f4": 2068,
    "f5": 5436,
    "f6": 8121,
    "f7": 2328
  },
  {
    "f0": 1456,
    "f1": 9846,
    "f2": 4206,
    "f3": 4228,
    "f4": 7647,
    "f5": 4947,
    "f6": 2541,
    "f7": 1961
  },
  {
    "f0": 9181,
    "f1": 4421,
    "f2": 3276,
    "f3": 3859,
    "f4": 7918,
    "f5": 1878,
    "f6": 9903,
    "f7": 8693
  },
  {
    "f0": 152,
    "f1": 2179,
    "f2": 3788,
    "f3": 2209,
    "f4": 9868,
    "f5": 2359,
    "f6": 2463,
    "f7": 5923
  },
  {
    "f0": 1071,
    "f1": 8794,
    "f2": 2038,
    "f3": 615,
    "f4": 5158,
    "f5": 31,
    "f6": 1811,
    "f7": 8286
  },
  {
    "f0": 3390,
    "f1": 9777,
    "f2": 9805,
    "f3": 6163,
    "f4": 6043,
    "f5": 4610,
    "f6": 275,
    "f7": 5034
  },
  {
    "f0": 1308,
    "f1": 1099,
    "f2": 2000,
    "f3": 7553,
    "f4": 3875,
    "f5": 3865,
    "f6": 7740,
    "f7": 263
  },
  {
    "f0": 129,
    "f1": 3720,
    "f2": 5241,
    "f3": 1176,
    "f4": 8548,
    "f5": 5753,
    "f6": 6800,
    "f7": 5846
  },
  {
    "f0": 6433,
    "f1": 4563,
    "f2": 1968,
    "f3": 8445,
    "f4": 6782,
    "f5": 4792,
    "f6": 3638,
    "f7": 3851
  },
  {
    "f0": 5411,
    "f1": 1391,
    "f2": 5540,
    "f3": 3016,
    "f4": 7780,
    "f5": 1933,
    "f6": 2090,
    "f7": 2412
  },
  {
    "f0": 4770,
    "f1": 3714,
    "f2": 8734,
    "f3": 3676,
    "f4": 665,
    "f5": 778,
    "f6": 9880,
    "f7": 7470
  },
  {
    "f0": 1948,
    "f1": 9088,
    "f2": 1202,
    "f3": 1318,
    "f4": 6197,
    "f5": 3483,
    "f6": 8574,
    "f7": 847
  },
  {
    "f0": 2063,
    "f1": 2960,
    "f2": 1110,
    "f3": 7808,
    "f4": 3325,
    "f5": 8546,
    "f6": 729,
    "f7": 5389
  },
  {
    "f0": 3133,
    "f1": 6716,
    "f2": 2185,
    "f3": 287,
    "f4": 7283,
    "f5": 299,
    "f6": 7194,
    "f7": 2679
  },
  {
    "f0": 8814,
    "f1": 5839,
    "f2": 6960,
    "f3": 2117,
    "f4": 7695,
    "f5": 3203,
    "f6": 8393,
    "f7": 875
  },
  {
    "f0": 5039,
    "f1": 7268,
    "f2": 4439,
    "f3": 4323,
    "f4": 1690,
    "f5": 3534,
    "f6": 1313,
    "f7": 1142
  },
  {
    "f0": 6361,
    "f1": 1393,
    "f2": 9778,
    "f3": 8559,
    "f4": 3840,
    "f5": 8698,
    "f6": 4412,
    "f7": 9463
  },
  {
    "f0": 589,
    "f1": 1003,
    "f2": 4862,
    "f3": 9836,
    "f4": 3877,
    "f5": 2605,
    "f6": 4516,
    "f7": 5773
  },
  {
    "f0": 1268,
    "f1": 1987,
    "f2": 2554,
    "f3": 4842,
    "f4": 6217,
    "f5": 9460,
    "f6": 1224,
    "f7": 1908
  },
  {
    "f0": 2430,
    "f1": 2133,
    "f2": 94,
    "f3": 535,
    "f4": 8866,
    "f5": 9438,
    "f6": 3635,
    "f7": 5425
  },
  {
    "f0": 5237,
    "f1": 3338,
    "f2": 4980,
    "f3": 5099,
    "f4": 8498,
    "f5": 1338,
    "f6": 2219,
    "f7": 630
  },
  {
    "f0": 617,
    "f1": 6586,
    "f2": 3179,
    "f3": 468,
    "f4": 7617,
    "f5": 6917,
    "f6": 7448,
    "f7": 6419
  },
  {
    "f0": 2927,
    "f1": 2867,
    "f2": 9179,
    "f3": 2267,
    "f4": 6188,
    "f5": 2163,
    "f6": 266,
    "f7": 3416
  },
  {
    "f0": 3654,
    "f1": 3310,
    "f2": 8299,
    "f3": 8146,
    "f4": 5503,
    "f5": 9044,
    "f6": 7553,
    "f7": 8006
  },
  {
    "f0": 9291,
    "f1": 3260,
    "f2": 1632,
    "f3": 246,
    "f4": 7209,
    "f5": 4194,
    "f6": 9495,
    "f7": 3161
  },
  {
